### ISSUE TITLE
客户端sdk是这样写的吗?

### ISSUE THREAD

**Issue by lsz7575** [libxengine/XEngine_Authorize#48]
**Describe the bug**
通过sdk登录,出现错误,
//接受数据
if (!XClient_TCPSelect_RecvPkt(m_hSocket, &ptszMsgBuffer, &nMsgLen, &st_ProtocolHdr))
AuthClient_dwErrorCode = ERROR_AUTHORIZE_MODULE_CLIENT_RECV; 错误代码是这个

**以下是我写的代码,写错了吗?**
   // 创建连接器实例
   CAuthClient_Connector authClient = CAuthClient_Connector();
   // 连接到服务器
   if (!authClient.AuthClient_Connector_Connect("127.0.0.1", 5302) )
   {
       std::cerr << "连接到服务器失败，错误码：" << AuthClient_GetLastError() <<  std::endl;
       return -1;
   }
   
   // 登录到服务器
   if ( !authClient.AuthClient_Connector_Login("admin", "123123aa")  ) 
   {
       std::cerr << "登录失败，错误码：" << AuthClient_GetLastError() <<  std::endl;

**Comment by xengine-qyt** [comment]
服务器有返回数据吗?服务端打印的什么? 服务端有显示登录成功还是失败吗?

**Comment by lsz7575** [comment]
我懂了,谢谢.
