### ISSUE TITLE
建议几个新功能

### ISSUE THREAD

**Issue by Tina0595** [libxengine/XEngine_Authorize#63]
1.可以让开发者在配置中自助选择使用mysql数据库和DB数据库吗？
2.用户登录成功后能否返回token到客户端，客户端每次请求接口都携带这个token，服务端判断这个token是否到期等验证

**Comment by Tina0595** [comment]
1. 可以让开发者在配置中自助选择是使用mysql数据库和DB数据库
2. 用户登录成功后能否返回token到客户端，客户端每次请求接口都携带这个token，服务端判断这个token是否到期等验证
3. token要能按照权限分配的操作，比如VIP的权限只能查询和删除，那VIP没有更新权限。。。

**Comment by xengine-qyt** [comment]
#74
