### ISSUE TITLE
客户端与服务端加密传输bug

### ISSUE THREAD

**Issue by Tina0595** [libxengine/XEngine_Authorize#64]
例子里的tcp登录，我服务端和客户端都开启加密传输后服务端是显示登录成功了，在客户端显示（不明白的类型）

**Comment by xengine-qyt** [comment]
fixed: [5d56423a56631b4375fe1ccb80e876d5492634c9](https://github.com/libxengine/XEngine_Authorize/commit/5d56423a56631b4375fe1ccb80e876d5492634c9)
