### ISSUE TITLE
TCP协议登录时，用户充值类型为DAY或者CUSTOM时都会提示已经登陆

### ISSUE THREAD

**Issue by gyh990** [libxengine/XEngine_Authorize#78]
服务器日志：
2024-11-18 07:38:04 ERROR - [Func:XEngine_Client_TCPTask][Line:268]:客户端：58.223.118.200:30404，用户名：test011，多端登录失败，用户已经登录,类型:1

充值类型为second和time时可以正常登录

另外：我认为最常用的序列号功能为，使用1天的序列卡，根据当前时间自动加上序列卡的期限为用户的到期时间，现在无论是second还是day的充值方式在用户没有登录时都是停止计时的

**Comment by gyh990** [comment]
我查看了代码，发现在配置文件里把custom和day的多端登录设置为true就可以了，但是我明明没有二次登录为什么会判定为多端登录

**Comment by xengine-qyt** [comment]
多端登录是有问题.等改下,

另外：我认为最常用的序列号功能为，使用1天的序列卡，根据当前时间自动加上序列卡的期限为用户的到期时间，现在无论是second还是day的充值方式在用户没有登录时都是停止计时的

用户没登录说明没使用,如果还即时这是什么道理呢?如果你想要对方没登录也即时应该使用天数卡或者自定义卡...

**Comment by xengine-qyt** [comment]
已修复:https://github.com/libxengine/XEngine_Authorize/commit/d52f4f07b5590287ca6c80db0c7b282fb2172525

序列卡功能在文档里面有说明7.3节,目前暂时不做修改

**Comment by xengine-qyt** [comment]
#80 Resolved
